### ISSUE TITLE
Tabcomplete with Commands Annotations

### ISSUE THREAD

**Issue by thehuze** [hakan-krgn/spigot-injection#18]
How is TabComplete supposed to be implemented for commands made through the annotations?

**Comment by hakan-krgn** [comment]
There isn't a tab completion support, just there is a method for it in annotation.

**Comment by thehuze** [comment]
Didn't understand. What method are you talking about?

**Comment by hakan-krgn** [comment]
https://github.com/hakan-krgn/spigot-injection/blob/master/injection-command/src/main/java/com/hakan/spinjection/command/annotations/Command.java#L56

**Comment by thehuze** [comment]
So there is no way to implement Tabcomplete for @Subcommand commands at the moment?

**Comment by hakan-krgn** [comment]
Yes, no way to implement it without changing spigot-injection
